import '../../domain/entities/movie.dart';

const movies = "https://raw.githubusercontent.com/FEND16/movie-json-data/master/json/movies-coming-soon.json";
final fakeMovieList = [
  Movie(
      id: "1",
      title: "Game Night",
      year: "2018",
      genres: [
        "Drama",
      ],
      ratings: [
        2,
        10,
        1,
        10,
        6,
        2,
        5,
        2,
        9,
        7,
        5,
        3,
        7,
        7,
        1,
        4,
        5,
        9,
        2,
        8,
        10,
        8,
        1,
        10,
        7,
        10,
        8,
        6,
        7,
        6
      ],
      duration: "PT100M",
      releaseDate: "2018-02-28",
      storyline:
      "A group of friends who meet regularly for game nights find themselves trying to solve a murder mystery.",
      actors: ["Rachel McAdams", "Jesse Plemons", "Jason Bateman"],
      posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQxMDE5NDg0NV5BMl5BanBnXkFtZTgwNTA5MDE2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"),
  Movie(
      id: "2",
      title: "Game Night",
      year: "2018",
      genres: [
        "Drama",
      ],
      ratings: [
        2,
        10,
        1,
        10,
        6,
        2,
        5,
        2,
        9,
        7,
        5,
        3,
        7,
        7,
        1,
        4,
        5,
        9,
        2,
        8,
        10,
        8,
        1,
        10,
        7,
        10,
        8,
        6,
        7,
        6
      ],      duration: "PT100M",
      releaseDate: "2018-02-28",
      storyline:
      "A group of friends who meet regularly for game nights find themselves trying to solve a murder mystery.",
      actors: ["Rachel McAdams", "Jesse Plemons", "Jason Bateman"],
      posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQxMDE5NDg0NV5BMl5BanBnXkFtZTgwNTA5MDE2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"),
  Movie(
      id: "3",
      title: "Game Night",
      year: "2018",
      genres: [
        "Drama",
      ],
      ratings: [
        2,
        10,
        1,
        10,
        6,
        2,
        5,
        2,
        9,
        7,
        5,
        3,
        7,
        7,
        1,
        4,
        5,
        9,
        2,
        8,
        10,
        8,
        1,
        10,
        7,
        10,
        8,
        6,
        7,
        6
      ],
      duration: "PT100M",
      releaseDate: "2018-02-28",
      storyline:
      "A group of friends who meet regularly for game nights find themselves trying to solve a murder mystery.",
      actors: ["Rachel McAdams", "Jesse Plemons", "Jason Bateman"],
      posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQxMDE5NDg0NV5BMl5BanBnXkFtZTgwNTA5MDE2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg")
];